import type { Beca, Carrera, Institucion } from "./data";

/**
 * Contenido institucional de base para "Tu Futuro": universidades públicas,
 * formación técnica/docente y becas reales, para que la sección no arranque
 * vacía mientras el equipo directivo carga su propio contenido desde el
 * panel de administración (`/tu-futuro/admin`). Los `id` van prefijados con
 * "seed-" para no chocar nunca con filas reales de la base.
 *
 * Las distancias a Lobos son aproximadas (redondeadas a la decena de km) y
 * sirven solo de referencia orientativa, no como dato exacto de ruta.
 */

export const SEED_INSTITUCIONES: Institucion[] = [
  {
    id: "seed-unlu",
    nombre: "Universidad Nacional de Luján (UNLu)",
    tipo: "universidad",
    descripcion:
      "Universidad pública y gratuita con sede central en Luján, la más cercana a Lobos. Ofrece carreras en Ciencias Agrarias, Educación, Administración, Informática, Turismo y más.",
    historia: null,
    ciudad: "Luján, Buenos Aires",
    direccion: "Ruta 5 y Avenida Constitución, Luján",
    lat: -34.5703,
    lng: -59.1048,
    distancia_km: 55,
    como_llegar: "Por la RP 41 y RN 7, o en micro desde Lobos con combinación en Mercedes o Luján.",
    modalidad: "Presencial y a distancia",
    sitio_oficial: "https://www.unlu.edu.ar",
    info_inscripcion:
      "Inscripción online a través del sitio oficial, con curso de ingreso previo (CIU).",
    contacto: null,
    logo_url: null,
    imagen_url: null,
    anio_actualizacion: 2026,
    archivado: false,
  },
  {
    id: "seed-uba",
    nombre: "Universidad de Buenos Aires (UBA)",
    tipo: "universidad",
    descripcion:
      "La universidad pública más grande del país, con decenas de carreras de grado en todas las áreas. Ingreso a través del Ciclo Básico Común (CBC).",
    historia: null,
    ciudad: "Ciudad Autónoma de Buenos Aires",
    direccion: null,
    lat: -34.6037,
    lng: -58.3816,
    distancia_km: 100,
    como_llegar:
      "En micro o combi desde Lobos a Once/Liniers, con conexión a subte o colectivo según la facultad.",
    modalidad: "Presencial",
    sitio_oficial: "https://www.uba.ar",
    info_inscripcion: "Inscripción online al CBC según la carrera y facultad elegida.",
    contacto: null,
    logo_url: null,
    imagen_url: null,
    anio_actualizacion: 2026,
    archivado: false,
  },
  {
    id: "seed-unlp",
    nombre: "Universidad Nacional de La Plata (UNLP)",
    tipo: "universidad",
    descripcion:
      "Una de las universidades públicas más grandes del país, con más de 100 carreras: Medicina, Derecho, Ingeniería, Bellas Artes, Informática y muchas más.",
    historia: null,
    ciudad: "La Plata, Buenos Aires",
    direccion: null,
    lat: -34.9214,
    lng: -57.9544,
    distancia_km: 180,
    como_llegar:
      "Conviene combinar micro hasta Buenos Aires y luego a La Plata, o auto por autopista.",
    modalidad: "Presencial",
    sitio_oficial: "https://www.unlp.edu.ar",
    info_inscripcion: "Inscripción online (SIU Guaraní) y curso de ingreso según facultad.",
    contacto: null,
    logo_url: null,
    imagen_url: null,
    anio_actualizacion: 2026,
    archivado: false,
  },
  {
    id: "seed-unnoba",
    nombre: "Universidad Nacional del Noroeste de la Prov. de Bs. As. (UNNOBA)",
    tipo: "universidad",
    descripcion:
      "Universidad pública con sedes en Junín y Pergamino. Carreras en Salud, Ingeniería, Ciencias Económicas, Jurídicas y Tecnologías.",
    historia: null,
    ciudad: "Junín, Buenos Aires",
    direccion: null,
    lat: -34.5834,
    lng: -60.9433,
    distancia_km: 150,
    como_llegar: "Por la RN 5 hacia Junín, o en micro con combinación en Chivilcoy.",
    modalidad: "Presencial y a distancia",
    sitio_oficial: "https://www.unnoba.edu.ar",
    info_inscripcion:
      "Inscripción online desde el sitio oficial, con curso de ambientación universitaria.",
    contacto: null,
    logo_url: null,
    imagen_url: null,
    anio_actualizacion: 2026,
    archivado: false,
  },
  {
    id: "seed-utn",
    nombre: "Universidad Tecnológica Nacional (UTN)",
    tipo: "universidad",
    descripcion:
      "Universidad pública especializada en ingenierías y tecnicaturas técnicas, organizada en facultades regionales en distintas ciudades del país.",
    historia: null,
    ciudad: "Varias sedes (regionales)",
    direccion: null,
    lat: null,
    lng: null,
    distancia_km: 120,
    como_llegar: "Según la facultad regional elegida (por ejemplo La Plata o Haedo/Avellaneda).",
    modalidad: "Presencial",
    sitio_oficial: "https://www.utn.edu.ar",
    info_inscripcion: "Inscripción online por facultad regional; requiere curso de nivelación.",
    contacto: null,
    logo_url: null,
    imagen_url: null,
    anio_actualizacion: 2026,
    archivado: false,
  },
  {
    id: "seed-formacion-profesional",
    nombre: "Centros de Formación Profesional (CFP) de la provincia",
    tipo: "formacion_profesional",
    descripcion:
      "Red de escuelas técnicas y centros de formación profesional de la Dirección General de Cultura y Educación de la Provincia de Buenos Aires: electricidad, gastronomía, informática, soldadura, administración y más oficios con certificado oficial.",
    historia: null,
    ciudad: "Lobos y alrededores",
    direccion: null,
    lat: null,
    lng: null,
    distancia_km: 0,
    como_llegar:
      "Consultá la oferta y sede más cercana en el sitio oficial de la Dirección de Educación Técnico Profesional.",
    modalidad: "Presencial",
    sitio_oficial: "https://abc.gob.ar/educacion-tecnico-profesional",
    info_inscripcion:
      "La inscripción se realiza en cada CFP según su cronograma anual; consultá en Secretaría de la escuela.",
    contacto: null,
    logo_url: null,
    imagen_url: null,
    anio_actualizacion: 2026,
    archivado: false,
  },
  {
    id: "seed-isfd",
    nombre: "Institutos Superiores de Formación Docente y Técnica (ISFD)",
    tipo: "terciario",
    descripcion:
      "Red provincial de profesorados y tecnicaturas superiores (Educación Inicial, Primaria, Secundaria en distintas disciplinas, Enfermería, Analista de Sistemas, entre otras), con sedes distribuidas por toda la provincia.",
    historia: null,
    ciudad: "Región (varias sedes)",
    direccion: null,
    lat: null,
    lng: null,
    distancia_km: null,
    como_llegar:
      "El instituto más cercano puede variar; consultalo en el buscador oficial de la DGCyE o en Secretaría de la escuela.",
    modalidad: "Presencial",
    sitio_oficial: "https://abc.gob.ar/institutos-superiores-de-formacion-docente-y-tecnica",
    info_inscripcion:
      "Inscripción anual (habitualmente noviembre a marzo) en la sede elegida, sin examen de ingreso eliminatorio en la mayoría de los profesorados.",
    contacto: null,
    logo_url: null,
    imagen_url: null,
    anio_actualizacion: 2026,
    archivado: false,
  },
];

const inst = (id: string) => SEED_INSTITUCIONES.find((i) => i.id === id) ?? null;
const pickInst = (id: string) => {
  const i = inst(id);
  return i
    ? { id: i.id, nombre: i.nombre, ciudad: i.ciudad, distancia_km: i.distancia_km, tipo: i.tipo }
    : null;
};

export const SEED_CARRERAS: Carrera[] = [
  {
    id: "seed-c-agronomia-unlu",
    nombre: "Ingeniería Agronómica",
    area: "Ciencias Agrarias",
    descripcion: "Formación para el manejo de la producción agropecuaria, suelos y agroindustria.",
    duracion: "5 años",
    duracion_anios: 5,
    modalidad: "Presencial",
    requisitos: "Secundario completo y curso de ingreso.",
    materias: null,
    perfil: "Interés en el campo, la producción y las ciencias biológicas.",
    salidas_laborales:
      "Producción agropecuaria, asesoría técnica, organismos públicos y privados del agro.",
    enlace_oficial: "https://www.unlu.edu.ar",
    institucion_id: "seed-unlu",
    anio_actualizacion: 2026,
    archivado: false,
    instituciones: pickInst("seed-unlu"),
  },
  {
    id: "seed-c-educacion-unlu",
    nombre: "Profesorado y Licenciatura en Ciencias de la Educación",
    area: "Educación",
    descripcion:
      "Formación docente e investigación educativa, con salida como profesor/a y como licenciado/a.",
    duracion: "4 a 5 años",
    duracion_anios: 5,
    modalidad: "Presencial",
    requisitos: "Secundario completo.",
    materias: null,
    perfil: "Interés en enseñar, en la gestión educativa o en investigación.",
    salidas_laborales: "Docencia, gestión educativa, capacitación, investigación.",
    enlace_oficial: "https://www.unlu.edu.ar",
    institucion_id: "seed-unlu",
    anio_actualizacion: 2026,
    archivado: false,
    instituciones: pickInst("seed-unlu"),
  },
  {
    id: "seed-c-derecho-uba",
    nombre: "Abogacía",
    area: "Ciencias Jurídicas",
    descripcion:
      "Formación integral en derecho para el ejercicio profesional, la magistratura o la función pública.",
    duracion: "5 a 6 años",
    duracion_anios: 6,
    modalidad: "Presencial",
    requisitos: "Secundario completo y Ciclo Básico Común (CBC).",
    materias: null,
    perfil: "Interés en la argumentación, la justicia y la resolución de conflictos.",
    salidas_laborales: "Estudio jurídico, poder judicial, sector público, empresas.",
    enlace_oficial: "https://www.uba.ar",
    institucion_id: "seed-uba",
    anio_actualizacion: 2026,
    archivado: false,
    instituciones: pickInst("seed-uba"),
  },
  {
    id: "seed-c-medicina-uba",
    nombre: "Medicina",
    area: "Salud",
    descripcion:
      "Carrera de grado para formarse como médico/a generalista, con posterior especialización.",
    duracion: "6 años",
    duracion_anios: 6,
    modalidad: "Presencial",
    requisitos: "Secundario completo, CBC y examen de finalización del CBC específico de Medicina.",
    materias: null,
    perfil: "Vocación de servicio, interés en biología y ciencias de la salud.",
    salidas_laborales: "Hospitales, salud pública, investigación, consultorio particular.",
    enlace_oficial: "https://www.uba.ar",
    institucion_id: "seed-uba",
    anio_actualizacion: 2026,
    archivado: false,
    instituciones: pickInst("seed-uba"),
  },
  {
    id: "seed-c-ingenieria-utn",
    nombre: "Ingeniería (Industrial, Civil, Sistemas, Electromecánica y otras)",
    area: "Ingeniería",
    descripcion:
      "Distintas especialidades de ingeniería con fuerte formación técnica y salida laboral concreta.",
    duracion: "5 a 6 años",
    duracion_anios: 6,
    modalidad: "Presencial",
    requisitos: "Secundario completo y curso de nivelación (ingreso).",
    materias: null,
    perfil: "Interés en matemática, física y resolución de problemas técnicos.",
    salidas_laborales: "Industria, obras, tecnología, consultoría técnica.",
    enlace_oficial: "https://www.utn.edu.ar",
    institucion_id: "seed-utn",
    anio_actualizacion: 2026,
    archivado: false,
    instituciones: pickInst("seed-utn"),
  },
  {
    id: "seed-c-enfermeria-isfd",
    nombre: "Tecnicatura Superior en Enfermería",
    area: "Salud",
    descripcion:
      "Formación técnica para el cuidado de la salud en hospitales, centros de salud y domicilios.",
    duracion: "3 años",
    duracion_anios: 3,
    modalidad: "Presencial",
    requisitos: "Secundario completo.",
    materias: null,
    perfil: "Vocación de cuidado y trabajo en equipo con otros profesionales de la salud.",
    salidas_laborales: "Hospitales, centros de salud, geriátricos, atención domiciliaria.",
    enlace_oficial: "https://abc.gob.ar/institutos-superiores-de-formacion-docente-y-tecnica",
    institucion_id: "seed-isfd",
    anio_actualizacion: 2026,
    archivado: false,
    instituciones: pickInst("seed-isfd"),
  },
  {
    id: "seed-c-sistemas-isfd",
    nombre: "Tecnicatura Superior en Análisis de Sistemas / Programación",
    area: "Tecnología",
    descripcion:
      "Formación técnica en desarrollo de software, bases de datos y soporte de sistemas.",
    duracion: "3 años",
    duracion_anios: 3,
    modalidad: "Presencial y a distancia según sede",
    requisitos: "Secundario completo.",
    materias: null,
    perfil: "Interés en programación, lógica y tecnología.",
    salidas_laborales: "Desarrollo de software, soporte técnico, análisis de sistemas.",
    enlace_oficial: "https://abc.gob.ar/institutos-superiores-de-formacion-docente-y-tecnica",
    institucion_id: "seed-isfd",
    anio_actualizacion: 2026,
    archivado: false,
    instituciones: pickInst("seed-isfd"),
  },
  {
    id: "seed-c-oficios-cfp",
    nombre: "Cursos de oficios (electricidad, gastronomía, soldadura y más)",
    area: "Oficios",
    descripcion: "Formación profesional corta y certificada en oficios con salida laboral rápida.",
    duracion: "3 meses a 2 años según el curso",
    duracion_anios: 1,
    modalidad: "Presencial",
    requisitos: "Varía según el curso; muchos no piden secundario completo.",
    materias: null,
    perfil: "Interés en el trabajo práctico y la inserción laboral rápida.",
    salidas_laborales: "Trabajo independiente o en relación de dependencia en el oficio elegido.",
    enlace_oficial: "https://abc.gob.ar/educacion-tecnico-profesional",
    institucion_id: "seed-formacion-profesional",
    anio_actualizacion: 2026,
    archivado: false,
    instituciones: pickInst("seed-formacion-profesional"),
  },
];

export const SEED_BECAS: Beca[] = [
  {
    id: "seed-b-progresar",
    nombre: "Beca PROGRESAR",
    tipo: "nacional",
    descripcion:
      "Beca nacional (ANSES) para estudiantes de nivel secundario, terciario o universitario, con un monto mensual sujeto a la asistencia y el avance en la carrera.",
    requisitos:
      "Ser argentino/a o residente, y cumplir los requisitos de edad e ingresos del grupo familiar que fija ANSES.",
    fecha_inicio: null,
    fecha_cierre: null,
    enlace_oficial: "https://www.argentina.gob.ar/becas-progresar",
    anio_actualizacion: 2026,
  },
  {
    id: "seed-b-boleto-educativo",
    nombre: "Boleto Educativo Gratuito (BEG)",
    tipo: "provincial",
    descripcion:
      "Beneficio de la Provincia de Buenos Aires que cubre viajes gratuitos en transporte público para estudiantes que asisten a un establecimiento educativo fuera de su localidad.",
    requisitos:
      "Estar matriculado/a en un nivel educativo y tramitarlo a través de la escuela o institución.",
    fecha_inicio: null,
    fecha_cierre: null,
    enlace_oficial: "https://www.gba.gob.ar/transporte/boleto_educativo",
    anio_actualizacion: 2026,
  },
  {
    id: "seed-b-bienestar-universitario",
    nombre: "Becas y comedores de bienestar universitario",
    tipo: "universitaria",
    descripcion:
      "Cada universidad pública (UBA, UNLu, UNLP, UNNOBA, UTN y otras) tiene su propia Secretaría de Bienestar Estudiantil con becas de comedor, transporte, apuntes, conectividad y alojamiento para quienes se mudan a estudiar.",
    requisitos: "Varía según la universidad; se tramita una vez inscripto/a en la carrera.",
    fecha_inicio: null,
    fecha_cierre: null,
    enlace_oficial: null,
    anio_actualizacion: 2026,
  },
  {
    id: "seed-b-conectividad",
    nombre: "Progresar Conectividad",
    tipo: "nacional",
    descripcion:
      "Línea complementaria de la Beca PROGRESAR pensada para acceso a internet y equipamiento tecnológico para estudiar.",
    requisitos: "Estar dentro de los requisitos generales del programa PROGRESAR.",
    fecha_inicio: null,
    fecha_cierre: null,
    enlace_oficial: "https://www.argentina.gob.ar/becas-progresar",
    anio_actualizacion: 2026,
  },
];
