/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as TuFuturoRouteRouteImport } from './routes/tu-futuro/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TuFuturoRecursosRouteImport } from './routes/tu-futuro/recursos'
import { Route as TuFuturoNoticiasRouteImport } from './routes/tu-futuro/noticias'
import { Route as TuFuturoCompartirRouteImport } from './routes/tu-futuro/compartir'
import { Route as TuFuturoCalendarioRouteImport } from './routes/tu-futuro/calendario'
import { Route as TuFuturoBecasRouteImport } from './routes/tu-futuro/becas'
import { Route as TuFuturoAuthRouteImport } from './routes/tu-futuro/auth'
import { Route as ApiPublicMediaSplatRouteImport } from './routes/api/public/media/$'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const TuFuturoRouteRoute = TuFuturoRouteRouteImport.update({
  id: '/tu-futuro',
  path: '/tu-futuro',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TuFuturoRecursosRoute = TuFuturoRecursosRouteImport.update({
  id: '/recursos',
  path: '/recursos',
  getParentRoute: () => TuFuturoRouteRoute,
} as any)
const TuFuturoNoticiasRoute = TuFuturoNoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => TuFuturoRouteRoute,
} as any)
const TuFuturoCompartirRoute = TuFuturoCompartirRouteImport.update({
  id: '/compartir',
  path: '/compartir',
  getParentRoute: () => TuFuturoRouteRoute,
} as any)
const TuFuturoCalendarioRoute = TuFuturoCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => TuFuturoRouteRoute,
} as any)
const TuFuturoBecasRoute = TuFuturoBecasRouteImport.update({
  id: '/becas',
  path: '/becas',
  getParentRoute: () => TuFuturoRouteRoute,
} as any)
const TuFuturoAuthRoute = TuFuturoAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => TuFuturoRouteRoute,
} as any)
const ApiPublicMediaSplatRoute = ApiPublicMediaSplatRouteImport.update({
  id: '/api/public/media/$',
  path: '/api/public/media/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tu-futuro': typeof TuFuturoRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/tu-futuro/auth': typeof TuFuturoAuthRoute
  '/tu-futuro/becas': typeof TuFuturoBecasRoute
  '/tu-futuro/calendario': typeof TuFuturoCalendarioRoute
  '/tu-futuro/compartir': typeof TuFuturoCompartirRoute
  '/tu-futuro/noticias': typeof TuFuturoNoticiasRoute
  '/tu-futuro/recursos': typeof TuFuturoRecursosRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tu-futuro': typeof TuFuturoRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/tu-futuro/auth': typeof TuFuturoAuthRoute
  '/tu-futuro/becas': typeof TuFuturoBecasRoute
  '/tu-futuro/calendario': typeof TuFuturoCalendarioRoute
  '/tu-futuro/compartir': typeof TuFuturoCompartirRoute
  '/tu-futuro/noticias': typeof TuFuturoNoticiasRoute
  '/tu-futuro/recursos': typeof TuFuturoRecursosRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tu-futuro': typeof TuFuturoRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/tu-futuro/auth': typeof TuFuturoAuthRoute
  '/tu-futuro/becas': typeof TuFuturoBecasRoute
  '/tu-futuro/calendario': typeof TuFuturoCalendarioRoute
  '/tu-futuro/compartir': typeof TuFuturoCompartirRoute
  '/tu-futuro/noticias': typeof TuFuturoNoticiasRoute
  '/tu-futuro/recursos': typeof TuFuturoRecursosRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/tu-futuro'
    | '/admin'
    | '/tu-futuro/auth'
    | '/tu-futuro/becas'
    | '/tu-futuro/calendario'
    | '/tu-futuro/compartir'
    | '/tu-futuro/noticias'
    | '/tu-futuro/recursos'
    | '/api/public/media/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/tu-futuro'
    | '/admin'
    | '/tu-futuro/auth'
    | '/tu-futuro/becas'
    | '/tu-futuro/calendario'
    | '/tu-futuro/compartir'
    | '/tu-futuro/noticias'
    | '/tu-futuro/recursos'
    | '/api/public/media/$'
  id:
    | '__root__'
    | '/'
    | '/tu-futuro'
    | '/admin'
    | '/tu-futuro/auth'
    | '/tu-futuro/becas'
    | '/tu-futuro/calendario'
    | '/tu-futuro/compartir'
    | '/tu-futuro/noticias'
    | '/tu-futuro/recursos'
    | '/api/public/media/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TuFuturoRouteRoute: typeof TuFuturoRouteRouteWithChildren
  AdminRoute: typeof AdminRoute
  ApiPublicMediaSplatRoute: typeof ApiPublicMediaSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tu-futuro': {
      id: '/tu-futuro'
      path: '/tu-futuro'
      fullPath: '/tu-futuro'
      preLoaderRoute: typeof TuFuturoRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tu-futuro/recursos': {
      id: '/tu-futuro/recursos'
      path: '/recursos'
      fullPath: '/tu-futuro/recursos'
      preLoaderRoute: typeof TuFuturoRecursosRouteImport
      parentRoute: typeof TuFuturoRouteRoute
    }
    '/tu-futuro/noticias': {
      id: '/tu-futuro/noticias'
      path: '/noticias'
      fullPath: '/tu-futuro/noticias'
      preLoaderRoute: typeof TuFuturoNoticiasRouteImport
      parentRoute: typeof TuFuturoRouteRoute
    }
    '/tu-futuro/compartir': {
      id: '/tu-futuro/compartir'
      path: '/compartir'
      fullPath: '/tu-futuro/compartir'
      preLoaderRoute: typeof TuFuturoCompartirRouteImport
      parentRoute: typeof TuFuturoRouteRoute
    }
    '/tu-futuro/calendario': {
      id: '/tu-futuro/calendario'
      path: '/calendario'
      fullPath: '/tu-futuro/calendario'
      preLoaderRoute: typeof TuFuturoCalendarioRouteImport
      parentRoute: typeof TuFuturoRouteRoute
    }
    '/tu-futuro/becas': {
      id: '/tu-futuro/becas'
      path: '/becas'
      fullPath: '/tu-futuro/becas'
      preLoaderRoute: typeof TuFuturoBecasRouteImport
      parentRoute: typeof TuFuturoRouteRoute
    }
    '/tu-futuro/auth': {
      id: '/tu-futuro/auth'
      path: '/auth'
      fullPath: '/tu-futuro/auth'
      preLoaderRoute: typeof TuFuturoAuthRouteImport
      parentRoute: typeof TuFuturoRouteRoute
    }
    '/api/public/media/$': {
      id: '/api/public/media/$'
      path: '/api/public/media/$'
      fullPath: '/api/public/media/$'
      preLoaderRoute: typeof ApiPublicMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TuFuturoRouteRouteChildren {
  TuFuturoAuthRoute: typeof TuFuturoAuthRoute
  TuFuturoBecasRoute: typeof TuFuturoBecasRoute
  TuFuturoCalendarioRoute: typeof TuFuturoCalendarioRoute
  TuFuturoCompartirRoute: typeof TuFuturoCompartirRoute
  TuFuturoNoticiasRoute: typeof TuFuturoNoticiasRoute
  TuFuturoRecursosRoute: typeof TuFuturoRecursosRoute
}

const TuFuturoRouteRouteChildren: TuFuturoRouteRouteChildren = {
  TuFuturoAuthRoute: TuFuturoAuthRoute,
  TuFuturoBecasRoute: TuFuturoBecasRoute,
  TuFuturoCalendarioRoute: TuFuturoCalendarioRoute,
  TuFuturoCompartirRoute: TuFuturoCompartirRoute,
  TuFuturoNoticiasRoute: TuFuturoNoticiasRoute,
  TuFuturoRecursosRoute: TuFuturoRecursosRoute,
}

const TuFuturoRouteRouteWithChildren = TuFuturoRouteRoute._addFileChildren(
  TuFuturoRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TuFuturoRouteRoute: TuFuturoRouteRouteWithChildren,
  AdminRoute: AdminRoute,
  ApiPublicMediaSplatRoute: ApiPublicMediaSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
