/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BibliotecaRouteRouteImport } from './routes/biblioteca/route'
import { Route as HistoriaRouteImport } from './routes/historia'
import { Route as InstitucionRouteImport } from './routes/institucion'
import { Route as MasRouteImport } from './routes/mas'
import { Route as TuFuturoRouteRouteImport } from './routes/tu-futuro/route'
import { Route as BibliotecaIndexRouteImport } from './routes/biblioteca/index'
import { Route as BibliotecaAccesoRouteImport } from './routes/biblioteca/acceso'
import { Route as BibliotecaAsistenteRouteImport } from './routes/biblioteca/asistente'
import { Route as BibliotecaCalendarioRouteImport } from './routes/biblioteca/calendario'
import { Route as BibliotecaEstudianteRouteImport } from './routes/biblioteca/estudiante'
import { Route as BibliotecaFavoritosRouteImport } from './routes/biblioteca/favoritos'
import { Route as BibliotecaInicioRouteImport } from './routes/biblioteca/inicio'
import { Route as BibliotecaNotificacionesRouteImport } from './routes/biblioteca/notificaciones'
import { Route as BibliotecaNovedadesRouteImport } from './routes/biblioteca/novedades'
import { Route as BibliotecaPerfilRouteImport } from './routes/biblioteca/perfil'
import { Route as TuFuturoIndexRouteImport } from './routes/tu-futuro/index'
import { Route as TuFuturoAdminRouteImport } from './routes/tu-futuro/admin'
import { Route as TuFuturoAuthRouteImport } from './routes/tu-futuro/auth'
import { Route as TuFuturoBecasRouteImport } from './routes/tu-futuro/becas'
import { Route as TuFuturoCalendarioRouteImport } from './routes/tu-futuro/calendario'
import { Route as TuFuturoCaminosRouteImport } from './routes/tu-futuro/caminos'
import { Route as TuFuturoCarrerasRouteImport } from './routes/tu-futuro/carreras'
import { Route as TuFuturoCompartirRouteImport } from './routes/tu-futuro/compartir'
import { Route as TuFuturoMapaRouteImport } from './routes/tu-futuro/mapa'
import { Route as TuFuturoNoticiasRouteImport } from './routes/tu-futuro/noticias'
import { Route as TuFuturoRecursosRouteImport } from './routes/tu-futuro/recursos'
import { Route as TuFuturoTestRouteImport } from './routes/tu-futuro/test'
import { Route as BibliotecaIngresoRolRouteImport } from './routes/biblioteca/ingreso.$rol'
import { Route as BibliotecaMateriaCodeRouteImport } from './routes/biblioteca/materia.$code'
import { Route as BibliotecaPanelIndexRouteImport } from './routes/biblioteca/panel/index'
import { Route as BibliotecaPanelAdministracionRouteImport } from './routes/biblioteca/panel/administracion'
import { Route as BibliotecaPanelCalendarioRouteImport } from './routes/biblioteca/panel/calendario'
import { Route as BibliotecaPanelComunicadosRouteImport } from './routes/biblioteca/panel/comunicados'
import { Route as BibliotecaPanelConfiguracionRouteImport } from './routes/biblioteca/panel/configuracion'
import { Route as BibliotecaPanelNovedadesRouteImport } from './routes/biblioteca/panel/novedades'
import { Route as BibliotecaPanelRecursosRouteImport } from './routes/biblioteca/panel/recursos'
import { Route as BibliotecaRecursoIdRouteImport } from './routes/biblioteca/recurso.$id'
import { Route as TuFuturoInstitucionesIndexRouteImport } from './routes/tu-futuro/instituciones.index'
import { Route as TuFuturoInstitucionesIdRouteImport } from './routes/tu-futuro/instituciones.$id'
import { Route as ApiPublicBibliotecaSplatRouteImport } from './routes/api/public/biblioteca/$'
import { Route as ApiPublicMediaSplatRouteImport } from './routes/api/public/media/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRouteRoute = BibliotecaRouteRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriaRoute = HistoriaRouteImport.update({
  id: '/historia',
  path: '/historia',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitucionRoute = InstitucionRouteImport.update({
  id: '/institucion',
  path: '/institucion',
  getParentRoute: () => rootRouteImport,
} as any)
const MasRoute = MasRouteImport.update({
  id: '/mas',
  path: '/mas',
  getParentRoute: () => rootRouteImport,
} as any)
const TuFuturoRouteRoute = TuFuturoRouteRouteImport.update({
  id: '/tu-futuro',
  path: '/tu-futuro',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaIndexRoute = BibliotecaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BibliotecaRouteRoute,
} as any)
const BibliotecaAccesoRoute = BibliotecaAccesoRouteImport.update({
  id: '/acceso',
  path: '/acceso',
  getParentRoute: () => BibliotecaRouteRoute,
} as any)
const BibliotecaAsistenteRoute = BibliotecaAsistenteRouteImport.update({
  id: '/asistente',
  path: '/asistente',
  getParentRoute: () => BibliotecaRouteRoute,
} as any)
const BibliotecaCalendarioRoute = BibliotecaCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => BibliotecaRouteRoute,
} as any)
const BibliotecaEstudianteRoute = BibliotecaEstudianteRouteImport.update({
  id: '/estudiante',
  path: '/estudiante',
  getParentRoute: () => BibliotecaRouteRoute,
} as any)
const BibliotecaFavoritosRoute = BibliotecaFavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => BibliotecaRouteRoute,
} as any)
const BibliotecaInicioRoute = BibliotecaInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => BibliotecaRouteRoute,
} as any)
const BibliotecaNotificacionesRoute =
  BibliotecaNotificacionesRouteImport.update({
    id: '/notificaciones',
    path: '/notificaciones',
    getParentRoute: () => BibliotecaRouteRoute,
  } as any)
const BibliotecaNovedadesRoute = BibliotecaNovedadesRouteImport.update({
  id: '/novedades',
  path: '/novedades',
  getParentRoute: () => BibliotecaRouteRoute,
} as any)
const BibliotecaPerfilRoute = BibliotecaPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => BibliotecaRouteRoute,
} as any)
const TuFuturoIndexRoute = TuFuturoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TuFuturoRouteRoute,
} as any)
const TuFuturoAdminRoute = TuFuturoAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => TuFuturoRouteRoute,
} as any)
const TuFuturoAuthRoute = TuFuturoAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => TuFuturoRouteRoute,
} as any)
const TuFuturoBecasRoute = TuFuturoBecasRouteImport.update({
  id: '/becas',
  path: '/becas',
  getParentRoute: () => TuFuturoRouteRoute,
} as any)
const TuFuturoCalendarioRoute = TuFuturoCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => TuFuturoRouteRoute,
} as any)
const TuFuturoCaminosRoute = TuFuturoCaminosRouteImport.update({
  id: '/caminos',
  path: '/caminos',
  getParentRoute: () => TuFuturoRouteRoute,
} as any)
const TuFuturoCarrerasRoute = TuFuturoCarrerasRouteImport.update({
  id: '/carreras',
  path: '/carreras',
  getParentRoute: () => TuFuturoRouteRoute,
} as any)
const TuFuturoCompartirRoute = TuFuturoCompartirRouteImport.update({
  id: '/compartir',
  path: '/compartir',
  getParentRoute: () => TuFuturoRouteRoute,
} as any)
const TuFuturoMapaRoute = TuFuturoMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => TuFuturoRouteRoute,
} as any)
const TuFuturoNoticiasRoute = TuFuturoNoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => TuFuturoRouteRoute,
} as any)
const TuFuturoRecursosRoute = TuFuturoRecursosRouteImport.update({
  id: '/recursos',
  path: '/recursos',
  getParentRoute: () => TuFuturoRouteRoute,
} as any)
const TuFuturoTestRoute = TuFuturoTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => TuFuturoRouteRoute,
} as any)
const BibliotecaIngresoRolRoute = BibliotecaIngresoRolRouteImport.update({
  id: '/ingreso/$rol',
  path: '/ingreso/$rol',
  getParentRoute: () => BibliotecaRouteRoute,
} as any)
const BibliotecaMateriaCodeRoute = BibliotecaMateriaCodeRouteImport.update({
  id: '/materia/$code',
  path: '/materia/$code',
  getParentRoute: () => BibliotecaRouteRoute,
} as any)
const BibliotecaPanelIndexRoute = BibliotecaPanelIndexRouteImport.update({
  id: '/panel/',
  path: '/panel/',
  getParentRoute: () => BibliotecaRouteRoute,
} as any)
const BibliotecaPanelAdministracionRoute =
  BibliotecaPanelAdministracionRouteImport.update({
    id: '/panel/administracion',
    path: '/panel/administracion',
    getParentRoute: () => BibliotecaRouteRoute,
  } as any)
const BibliotecaPanelCalendarioRoute =
  BibliotecaPanelCalendarioRouteImport.update({
    id: '/panel/calendario',
    path: '/panel/calendario',
    getParentRoute: () => BibliotecaRouteRoute,
  } as any)
const BibliotecaPanelComunicadosRoute =
  BibliotecaPanelComunicadosRouteImport.update({
    id: '/panel/comunicados',
    path: '/panel/comunicados',
    getParentRoute: () => BibliotecaRouteRoute,
  } as any)
const BibliotecaPanelConfiguracionRoute =
  BibliotecaPanelConfiguracionRouteImport.update({
    id: '/panel/configuracion',
    path: '/panel/configuracion',
    getParentRoute: () => BibliotecaRouteRoute,
  } as any)
const BibliotecaPanelNovedadesRoute =
  BibliotecaPanelNovedadesRouteImport.update({
    id: '/panel/novedades',
    path: '/panel/novedades',
    getParentRoute: () => BibliotecaRouteRoute,
  } as any)
const BibliotecaPanelRecursosRoute = BibliotecaPanelRecursosRouteImport.update({
  id: '/panel/recursos',
  path: '/panel/recursos',
  getParentRoute: () => BibliotecaRouteRoute,
} as any)
const BibliotecaRecursoIdRoute = BibliotecaRecursoIdRouteImport.update({
  id: '/recurso/$id',
  path: '/recurso/$id',
  getParentRoute: () => BibliotecaRouteRoute,
} as any)
const TuFuturoInstitucionesIndexRoute =
  TuFuturoInstitucionesIndexRouteImport.update({
    id: '/instituciones/',
    path: '/instituciones/',
    getParentRoute: () => TuFuturoRouteRoute,
  } as any)
const TuFuturoInstitucionesIdRoute = TuFuturoInstitucionesIdRouteImport.update({
  id: '/instituciones/$id',
  path: '/instituciones/$id',
  getParentRoute: () => TuFuturoRouteRoute,
} as any)
const ApiPublicBibliotecaSplatRoute =
  ApiPublicBibliotecaSplatRouteImport.update({
    id: '/api/public/biblioteca/$',
    path: '/api/public/biblioteca/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMediaSplatRoute = ApiPublicMediaSplatRouteImport.update({
  id: '/api/public/media/$',
  path: '/api/public/media/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRouteRouteWithChildren
  '/tu-futuro': typeof TuFuturoRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/historia': typeof HistoriaRoute
  '/institucion': typeof InstitucionRoute
  '/mas': typeof MasRoute
  '/biblioteca/acceso': typeof BibliotecaAccesoRoute
  '/biblioteca/asistente': typeof BibliotecaAsistenteRoute
  '/biblioteca/calendario': typeof BibliotecaCalendarioRoute
  '/biblioteca/estudiante': typeof BibliotecaEstudianteRoute
  '/biblioteca/favoritos': typeof BibliotecaFavoritosRoute
  '/biblioteca/inicio': typeof BibliotecaInicioRoute
  '/biblioteca/notificaciones': typeof BibliotecaNotificacionesRoute
  '/biblioteca/novedades': typeof BibliotecaNovedadesRoute
  '/biblioteca/perfil': typeof BibliotecaPerfilRoute
  '/tu-futuro/admin': typeof TuFuturoAdminRoute
  '/tu-futuro/auth': typeof TuFuturoAuthRoute
  '/tu-futuro/becas': typeof TuFuturoBecasRoute
  '/tu-futuro/calendario': typeof TuFuturoCalendarioRoute
  '/tu-futuro/caminos': typeof TuFuturoCaminosRoute
  '/tu-futuro/carreras': typeof TuFuturoCarrerasRoute
  '/tu-futuro/compartir': typeof TuFuturoCompartirRoute
  '/tu-futuro/mapa': typeof TuFuturoMapaRoute
  '/tu-futuro/noticias': typeof TuFuturoNoticiasRoute
  '/tu-futuro/recursos': typeof TuFuturoRecursosRoute
  '/tu-futuro/test': typeof TuFuturoTestRoute
  '/biblioteca/': typeof BibliotecaIndexRoute
  '/tu-futuro/': typeof TuFuturoIndexRoute
  '/biblioteca/ingreso/$rol': typeof BibliotecaIngresoRolRoute
  '/biblioteca/materia/$code': typeof BibliotecaMateriaCodeRoute
  '/biblioteca/panel/administracion': typeof BibliotecaPanelAdministracionRoute
  '/biblioteca/panel/calendario': typeof BibliotecaPanelCalendarioRoute
  '/biblioteca/panel/comunicados': typeof BibliotecaPanelComunicadosRoute
  '/biblioteca/panel/configuracion': typeof BibliotecaPanelConfiguracionRoute
  '/biblioteca/panel/novedades': typeof BibliotecaPanelNovedadesRoute
  '/biblioteca/panel/recursos': typeof BibliotecaPanelRecursosRoute
  '/biblioteca/recurso/$id': typeof BibliotecaRecursoIdRoute
  '/tu-futuro/instituciones/$id': typeof TuFuturoInstitucionesIdRoute
  '/biblioteca/panel/': typeof BibliotecaPanelIndexRoute
  '/tu-futuro/instituciones/': typeof TuFuturoInstitucionesIndexRoute
  '/api/public/biblioteca/$': typeof ApiPublicBibliotecaSplatRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/historia': typeof HistoriaRoute
  '/institucion': typeof InstitucionRoute
  '/mas': typeof MasRoute
  '/biblioteca/acceso': typeof BibliotecaAccesoRoute
  '/biblioteca/asistente': typeof BibliotecaAsistenteRoute
  '/biblioteca/calendario': typeof BibliotecaCalendarioRoute
  '/biblioteca/estudiante': typeof BibliotecaEstudianteRoute
  '/biblioteca/favoritos': typeof BibliotecaFavoritosRoute
  '/biblioteca/inicio': typeof BibliotecaInicioRoute
  '/biblioteca/notificaciones': typeof BibliotecaNotificacionesRoute
  '/biblioteca/novedades': typeof BibliotecaNovedadesRoute
  '/biblioteca/perfil': typeof BibliotecaPerfilRoute
  '/tu-futuro/admin': typeof TuFuturoAdminRoute
  '/tu-futuro/auth': typeof TuFuturoAuthRoute
  '/tu-futuro/becas': typeof TuFuturoBecasRoute
  '/tu-futuro/calendario': typeof TuFuturoCalendarioRoute
  '/tu-futuro/caminos': typeof TuFuturoCaminosRoute
  '/tu-futuro/carreras': typeof TuFuturoCarrerasRoute
  '/tu-futuro/compartir': typeof TuFuturoCompartirRoute
  '/tu-futuro/mapa': typeof TuFuturoMapaRoute
  '/tu-futuro/noticias': typeof TuFuturoNoticiasRoute
  '/tu-futuro/recursos': typeof TuFuturoRecursosRoute
  '/tu-futuro/test': typeof TuFuturoTestRoute
  '/biblioteca': typeof BibliotecaIndexRoute
  '/tu-futuro': typeof TuFuturoIndexRoute
  '/biblioteca/ingreso/$rol': typeof BibliotecaIngresoRolRoute
  '/biblioteca/materia/$code': typeof BibliotecaMateriaCodeRoute
  '/biblioteca/panel/administracion': typeof BibliotecaPanelAdministracionRoute
  '/biblioteca/panel/calendario': typeof BibliotecaPanelCalendarioRoute
  '/biblioteca/panel/comunicados': typeof BibliotecaPanelComunicadosRoute
  '/biblioteca/panel/configuracion': typeof BibliotecaPanelConfiguracionRoute
  '/biblioteca/panel/novedades': typeof BibliotecaPanelNovedadesRoute
  '/biblioteca/panel/recursos': typeof BibliotecaPanelRecursosRoute
  '/biblioteca/recurso/$id': typeof BibliotecaRecursoIdRoute
  '/tu-futuro/instituciones/$id': typeof TuFuturoInstitucionesIdRoute
  '/biblioteca/panel': typeof BibliotecaPanelIndexRoute
  '/tu-futuro/instituciones': typeof TuFuturoInstitucionesIndexRoute
  '/api/public/biblioteca/$': typeof ApiPublicBibliotecaSplatRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRouteRouteWithChildren
  '/tu-futuro': typeof TuFuturoRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/historia': typeof HistoriaRoute
  '/institucion': typeof InstitucionRoute
  '/mas': typeof MasRoute
  '/biblioteca/acceso': typeof BibliotecaAccesoRoute
  '/biblioteca/asistente': typeof BibliotecaAsistenteRoute
  '/biblioteca/calendario': typeof BibliotecaCalendarioRoute
  '/biblioteca/estudiante': typeof BibliotecaEstudianteRoute
  '/biblioteca/favoritos': typeof BibliotecaFavoritosRoute
  '/biblioteca/inicio': typeof BibliotecaInicioRoute
  '/biblioteca/notificaciones': typeof BibliotecaNotificacionesRoute
  '/biblioteca/novedades': typeof BibliotecaNovedadesRoute
  '/biblioteca/perfil': typeof BibliotecaPerfilRoute
  '/tu-futuro/admin': typeof TuFuturoAdminRoute
  '/tu-futuro/auth': typeof TuFuturoAuthRoute
  '/tu-futuro/becas': typeof TuFuturoBecasRoute
  '/tu-futuro/calendario': typeof TuFuturoCalendarioRoute
  '/tu-futuro/caminos': typeof TuFuturoCaminosRoute
  '/tu-futuro/carreras': typeof TuFuturoCarrerasRoute
  '/tu-futuro/compartir': typeof TuFuturoCompartirRoute
  '/tu-futuro/mapa': typeof TuFuturoMapaRoute
  '/tu-futuro/noticias': typeof TuFuturoNoticiasRoute
  '/tu-futuro/recursos': typeof TuFuturoRecursosRoute
  '/tu-futuro/test': typeof TuFuturoTestRoute
  '/biblioteca/': typeof BibliotecaIndexRoute
  '/tu-futuro/': typeof TuFuturoIndexRoute
  '/biblioteca/ingreso/$rol': typeof BibliotecaIngresoRolRoute
  '/biblioteca/materia/$code': typeof BibliotecaMateriaCodeRoute
  '/biblioteca/panel/administracion': typeof BibliotecaPanelAdministracionRoute
  '/biblioteca/panel/calendario': typeof BibliotecaPanelCalendarioRoute
  '/biblioteca/panel/comunicados': typeof BibliotecaPanelComunicadosRoute
  '/biblioteca/panel/configuracion': typeof BibliotecaPanelConfiguracionRoute
  '/biblioteca/panel/novedades': typeof BibliotecaPanelNovedadesRoute
  '/biblioteca/panel/recursos': typeof BibliotecaPanelRecursosRoute
  '/biblioteca/recurso/$id': typeof BibliotecaRecursoIdRoute
  '/tu-futuro/instituciones/$id': typeof TuFuturoInstitucionesIdRoute
  '/biblioteca/panel/': typeof BibliotecaPanelIndexRoute
  '/tu-futuro/instituciones/': typeof TuFuturoInstitucionesIndexRoute
  '/api/public/biblioteca/$': typeof ApiPublicBibliotecaSplatRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/biblioteca'
    | '/tu-futuro'
    | '/admin'
    | '/historia'
    | '/institucion'
    | '/mas'
    | '/biblioteca/acceso'
    | '/biblioteca/asistente'
    | '/biblioteca/calendario'
    | '/biblioteca/estudiante'
    | '/biblioteca/favoritos'
    | '/biblioteca/inicio'
    | '/biblioteca/notificaciones'
    | '/biblioteca/novedades'
    | '/biblioteca/perfil'
    | '/tu-futuro/admin'
    | '/tu-futuro/auth'
    | '/tu-futuro/becas'
    | '/tu-futuro/calendario'
    | '/tu-futuro/caminos'
    | '/tu-futuro/carreras'
    | '/tu-futuro/compartir'
    | '/tu-futuro/mapa'
    | '/tu-futuro/noticias'
    | '/tu-futuro/recursos'
    | '/tu-futuro/test'
    | '/biblioteca/'
    | '/tu-futuro/'
    | '/biblioteca/ingreso/$rol'
    | '/biblioteca/materia/$code'
    | '/biblioteca/panel/administracion'
    | '/biblioteca/panel/calendario'
    | '/biblioteca/panel/comunicados'
    | '/biblioteca/panel/configuracion'
    | '/biblioteca/panel/novedades'
    | '/biblioteca/panel/recursos'
    | '/biblioteca/recurso/$id'
    | '/tu-futuro/instituciones/$id'
    | '/biblioteca/panel/'
    | '/tu-futuro/instituciones/'
    | '/api/public/biblioteca/$'
    | '/api/public/media/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/historia'
    | '/institucion'
    | '/mas'
    | '/biblioteca/acceso'
    | '/biblioteca/asistente'
    | '/biblioteca/calendario'
    | '/biblioteca/estudiante'
    | '/biblioteca/favoritos'
    | '/biblioteca/inicio'
    | '/biblioteca/notificaciones'
    | '/biblioteca/novedades'
    | '/biblioteca/perfil'
    | '/tu-futuro/admin'
    | '/tu-futuro/auth'
    | '/tu-futuro/becas'
    | '/tu-futuro/calendario'
    | '/tu-futuro/caminos'
    | '/tu-futuro/carreras'
    | '/tu-futuro/compartir'
    | '/tu-futuro/mapa'
    | '/tu-futuro/noticias'
    | '/tu-futuro/recursos'
    | '/tu-futuro/test'
    | '/biblioteca'
    | '/tu-futuro'
    | '/biblioteca/ingreso/$rol'
    | '/biblioteca/materia/$code'
    | '/biblioteca/panel/administracion'
    | '/biblioteca/panel/calendario'
    | '/biblioteca/panel/comunicados'
    | '/biblioteca/panel/configuracion'
    | '/biblioteca/panel/novedades'
    | '/biblioteca/panel/recursos'
    | '/biblioteca/recurso/$id'
    | '/tu-futuro/instituciones/$id'
    | '/biblioteca/panel'
    | '/tu-futuro/instituciones'
    | '/api/public/biblioteca/$'
    | '/api/public/media/$'
  id:
    | '__root__'
    | '/'
    | '/biblioteca'
    | '/tu-futuro'
    | '/admin'
    | '/historia'
    | '/institucion'
    | '/mas'
    | '/biblioteca/acceso'
    | '/biblioteca/asistente'
    | '/biblioteca/calendario'
    | '/biblioteca/estudiante'
    | '/biblioteca/favoritos'
    | '/biblioteca/inicio'
    | '/biblioteca/notificaciones'
    | '/biblioteca/novedades'
    | '/biblioteca/perfil'
    | '/tu-futuro/admin'
    | '/tu-futuro/auth'
    | '/tu-futuro/becas'
    | '/tu-futuro/calendario'
    | '/tu-futuro/caminos'
    | '/tu-futuro/carreras'
    | '/tu-futuro/compartir'
    | '/tu-futuro/mapa'
    | '/tu-futuro/noticias'
    | '/tu-futuro/recursos'
    | '/tu-futuro/test'
    | '/biblioteca/'
    | '/tu-futuro/'
    | '/biblioteca/ingreso/$rol'
    | '/biblioteca/materia/$code'
    | '/biblioteca/panel/administracion'
    | '/biblioteca/panel/calendario'
    | '/biblioteca/panel/comunicados'
    | '/biblioteca/panel/configuracion'
    | '/biblioteca/panel/novedades'
    | '/biblioteca/panel/recursos'
    | '/biblioteca/recurso/$id'
    | '/tu-futuro/instituciones/$id'
    | '/biblioteca/panel/'
    | '/tu-futuro/instituciones/'
    | '/api/public/biblioteca/$'
    | '/api/public/media/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BibliotecaRouteRoute: typeof BibliotecaRouteRouteWithChildren
  TuFuturoRouteRoute: typeof TuFuturoRouteRouteWithChildren
  AdminRoute: typeof AdminRoute
  HistoriaRoute: typeof HistoriaRoute
  InstitucionRoute: typeof InstitucionRoute
  MasRoute: typeof MasRoute
  ApiPublicBibliotecaSplatRoute: typeof ApiPublicBibliotecaSplatRoute
  ApiPublicMediaSplatRoute: typeof ApiPublicMediaSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historia': {
      id: '/historia'
      path: '/historia'
      fullPath: '/historia'
      preLoaderRoute: typeof HistoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institucion': {
      id: '/institucion'
      path: '/institucion'
      fullPath: '/institucion'
      preLoaderRoute: typeof InstitucionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mas': {
      id: '/mas'
      path: '/mas'
      fullPath: '/mas'
      preLoaderRoute: typeof MasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tu-futuro': {
      id: '/tu-futuro'
      path: '/tu-futuro'
      fullPath: '/tu-futuro'
      preLoaderRoute: typeof TuFuturoRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca/': {
      id: '/biblioteca/'
      path: '/'
      fullPath: '/biblioteca/'
      preLoaderRoute: typeof BibliotecaIndexRouteImport
      parentRoute: typeof BibliotecaRouteRoute
    }
    '/biblioteca/acceso': {
      id: '/biblioteca/acceso'
      path: '/acceso'
      fullPath: '/biblioteca/acceso'
      preLoaderRoute: typeof BibliotecaAccesoRouteImport
      parentRoute: typeof BibliotecaRouteRoute
    }
    '/biblioteca/asistente': {
      id: '/biblioteca/asistente'
      path: '/asistente'
      fullPath: '/biblioteca/asistente'
      preLoaderRoute: typeof BibliotecaAsistenteRouteImport
      parentRoute: typeof BibliotecaRouteRoute
    }
    '/biblioteca/calendario': {
      id: '/biblioteca/calendario'
      path: '/calendario'
      fullPath: '/biblioteca/calendario'
      preLoaderRoute: typeof BibliotecaCalendarioRouteImport
      parentRoute: typeof BibliotecaRouteRoute
    }
    '/biblioteca/estudiante': {
      id: '/biblioteca/estudiante'
      path: '/estudiante'
      fullPath: '/biblioteca/estudiante'
      preLoaderRoute: typeof BibliotecaEstudianteRouteImport
      parentRoute: typeof BibliotecaRouteRoute
    }
    '/biblioteca/favoritos': {
      id: '/biblioteca/favoritos'
      path: '/favoritos'
      fullPath: '/biblioteca/favoritos'
      preLoaderRoute: typeof BibliotecaFavoritosRouteImport
      parentRoute: typeof BibliotecaRouteRoute
    }
    '/biblioteca/inicio': {
      id: '/biblioteca/inicio'
      path: '/inicio'
      fullPath: '/biblioteca/inicio'
      preLoaderRoute: typeof BibliotecaInicioRouteImport
      parentRoute: typeof BibliotecaRouteRoute
    }
    '/biblioteca/notificaciones': {
      id: '/biblioteca/notificaciones'
      path: '/notificaciones'
      fullPath: '/biblioteca/notificaciones'
      preLoaderRoute: typeof BibliotecaNotificacionesRouteImport
      parentRoute: typeof BibliotecaRouteRoute
    }
    '/biblioteca/novedades': {
      id: '/biblioteca/novedades'
      path: '/novedades'
      fullPath: '/biblioteca/novedades'
      preLoaderRoute: typeof BibliotecaNovedadesRouteImport
      parentRoute: typeof BibliotecaRouteRoute
    }
    '/biblioteca/perfil': {
      id: '/biblioteca/perfil'
      path: '/perfil'
      fullPath: '/biblioteca/perfil'
      preLoaderRoute: typeof BibliotecaPerfilRouteImport
      parentRoute: typeof BibliotecaRouteRoute
    }
    '/tu-futuro/': {
      id: '/tu-futuro/'
      path: '/'
      fullPath: '/tu-futuro/'
      preLoaderRoute: typeof TuFuturoIndexRouteImport
      parentRoute: typeof TuFuturoRouteRoute
    }
    '/tu-futuro/admin': {
      id: '/tu-futuro/admin'
      path: '/admin'
      fullPath: '/tu-futuro/admin'
      preLoaderRoute: typeof TuFuturoAdminRouteImport
      parentRoute: typeof TuFuturoRouteRoute
    }
    '/tu-futuro/auth': {
      id: '/tu-futuro/auth'
      path: '/auth'
      fullPath: '/tu-futuro/auth'
      preLoaderRoute: typeof TuFuturoAuthRouteImport
      parentRoute: typeof TuFuturoRouteRoute
    }
    '/tu-futuro/becas': {
      id: '/tu-futuro/becas'
      path: '/becas'
      fullPath: '/tu-futuro/becas'
      preLoaderRoute: typeof TuFuturoBecasRouteImport
      parentRoute: typeof TuFuturoRouteRoute
    }
    '/tu-futuro/calendario': {
      id: '/tu-futuro/calendario'
      path: '/calendario'
      fullPath: '/tu-futuro/calendario'
      preLoaderRoute: typeof TuFuturoCalendarioRouteImport
      parentRoute: typeof TuFuturoRouteRoute
    }
    '/tu-futuro/caminos': {
      id: '/tu-futuro/caminos'
      path: '/caminos'
      fullPath: '/tu-futuro/caminos'
      preLoaderRoute: typeof TuFuturoCaminosRouteImport
      parentRoute: typeof TuFuturoRouteRoute
    }
    '/tu-futuro/carreras': {
      id: '/tu-futuro/carreras'
      path: '/carreras'
      fullPath: '/tu-futuro/carreras'
      preLoaderRoute: typeof TuFuturoCarrerasRouteImport
      parentRoute: typeof TuFuturoRouteRoute
    }
    '/tu-futuro/compartir': {
      id: '/tu-futuro/compartir'
      path: '/compartir'
      fullPath: '/tu-futuro/compartir'
      preLoaderRoute: typeof TuFuturoCompartirRouteImport
      parentRoute: typeof TuFuturoRouteRoute
    }
    '/tu-futuro/mapa': {
      id: '/tu-futuro/mapa'
      path: '/mapa'
      fullPath: '/tu-futuro/mapa'
      preLoaderRoute: typeof TuFuturoMapaRouteImport
      parentRoute: typeof TuFuturoRouteRoute
    }
    '/tu-futuro/noticias': {
      id: '/tu-futuro/noticias'
      path: '/noticias'
      fullPath: '/tu-futuro/noticias'
      preLoaderRoute: typeof TuFuturoNoticiasRouteImport
      parentRoute: typeof TuFuturoRouteRoute
    }
    '/tu-futuro/recursos': {
      id: '/tu-futuro/recursos'
      path: '/recursos'
      fullPath: '/tu-futuro/recursos'
      preLoaderRoute: typeof TuFuturoRecursosRouteImport
      parentRoute: typeof TuFuturoRouteRoute
    }
    '/tu-futuro/test': {
      id: '/tu-futuro/test'
      path: '/test'
      fullPath: '/tu-futuro/test'
      preLoaderRoute: typeof TuFuturoTestRouteImport
      parentRoute: typeof TuFuturoRouteRoute
    }
    '/biblioteca/ingreso/$rol': {
      id: '/biblioteca/ingreso/$rol'
      path: '/ingreso/$rol'
      fullPath: '/biblioteca/ingreso/$rol'
      preLoaderRoute: typeof BibliotecaIngresoRolRouteImport
      parentRoute: typeof BibliotecaRouteRoute
    }
    '/biblioteca/materia/$code': {
      id: '/biblioteca/materia/$code'
      path: '/materia/$code'
      fullPath: '/biblioteca/materia/$code'
      preLoaderRoute: typeof BibliotecaMateriaCodeRouteImport
      parentRoute: typeof BibliotecaRouteRoute
    }
    '/biblioteca/panel/': {
      id: '/biblioteca/panel/'
      path: '/panel'
      fullPath: '/biblioteca/panel/'
      preLoaderRoute: typeof BibliotecaPanelIndexRouteImport
      parentRoute: typeof BibliotecaRouteRoute
    }
    '/biblioteca/panel/administracion': {
      id: '/biblioteca/panel/administracion'
      path: '/panel/administracion'
      fullPath: '/biblioteca/panel/administracion'
      preLoaderRoute: typeof BibliotecaPanelAdministracionRouteImport
      parentRoute: typeof BibliotecaRouteRoute
    }
    '/biblioteca/panel/calendario': {
      id: '/biblioteca/panel/calendario'
      path: '/panel/calendario'
      fullPath: '/biblioteca/panel/calendario'
      preLoaderRoute: typeof BibliotecaPanelCalendarioRouteImport
      parentRoute: typeof BibliotecaRouteRoute
    }
    '/biblioteca/panel/comunicados': {
      id: '/biblioteca/panel/comunicados'
      path: '/panel/comunicados'
      fullPath: '/biblioteca/panel/comunicados'
      preLoaderRoute: typeof BibliotecaPanelComunicadosRouteImport
      parentRoute: typeof BibliotecaRouteRoute
    }
    '/biblioteca/panel/configuracion': {
      id: '/biblioteca/panel/configuracion'
      path: '/panel/configuracion'
      fullPath: '/biblioteca/panel/configuracion'
      preLoaderRoute: typeof BibliotecaPanelConfiguracionRouteImport
      parentRoute: typeof BibliotecaRouteRoute
    }
    '/biblioteca/panel/novedades': {
      id: '/biblioteca/panel/novedades'
      path: '/panel/novedades'
      fullPath: '/biblioteca/panel/novedades'
      preLoaderRoute: typeof BibliotecaPanelNovedadesRouteImport
      parentRoute: typeof BibliotecaRouteRoute
    }
    '/biblioteca/panel/recursos': {
      id: '/biblioteca/panel/recursos'
      path: '/panel/recursos'
      fullPath: '/biblioteca/panel/recursos'
      preLoaderRoute: typeof BibliotecaPanelRecursosRouteImport
      parentRoute: typeof BibliotecaRouteRoute
    }
    '/biblioteca/recurso/$id': {
      id: '/biblioteca/recurso/$id'
      path: '/recurso/$id'
      fullPath: '/biblioteca/recurso/$id'
      preLoaderRoute: typeof BibliotecaRecursoIdRouteImport
      parentRoute: typeof BibliotecaRouteRoute
    }
    '/tu-futuro/instituciones/': {
      id: '/tu-futuro/instituciones/'
      path: '/instituciones'
      fullPath: '/tu-futuro/instituciones/'
      preLoaderRoute: typeof TuFuturoInstitucionesIndexRouteImport
      parentRoute: typeof TuFuturoRouteRoute
    }
    '/tu-futuro/instituciones/$id': {
      id: '/tu-futuro/instituciones/$id'
      path: '/instituciones/$id'
      fullPath: '/tu-futuro/instituciones/$id'
      preLoaderRoute: typeof TuFuturoInstitucionesIdRouteImport
      parentRoute: typeof TuFuturoRouteRoute
    }
    '/api/public/biblioteca/$': {
      id: '/api/public/biblioteca/$'
      path: '/api/public/biblioteca/$'
      fullPath: '/api/public/biblioteca/$'
      preLoaderRoute: typeof ApiPublicBibliotecaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/media/$': {
      id: '/api/public/media/$'
      path: '/api/public/media/$'
      fullPath: '/api/public/media/$'
      preLoaderRoute: typeof ApiPublicMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BibliotecaRouteRouteChildren {
  BibliotecaAccesoRoute: typeof BibliotecaAccesoRoute
  BibliotecaAsistenteRoute: typeof BibliotecaAsistenteRoute
  BibliotecaCalendarioRoute: typeof BibliotecaCalendarioRoute
  BibliotecaEstudianteRoute: typeof BibliotecaEstudianteRoute
  BibliotecaFavoritosRoute: typeof BibliotecaFavoritosRoute
  BibliotecaInicioRoute: typeof BibliotecaInicioRoute
  BibliotecaNotificacionesRoute: typeof BibliotecaNotificacionesRoute
  BibliotecaNovedadesRoute: typeof BibliotecaNovedadesRoute
  BibliotecaPerfilRoute: typeof BibliotecaPerfilRoute
  BibliotecaIndexRoute: typeof BibliotecaIndexRoute
  BibliotecaIngresoRolRoute: typeof BibliotecaIngresoRolRoute
  BibliotecaMateriaCodeRoute: typeof BibliotecaMateriaCodeRoute
  BibliotecaPanelAdministracionRoute: typeof BibliotecaPanelAdministracionRoute
  BibliotecaPanelCalendarioRoute: typeof BibliotecaPanelCalendarioRoute
  BibliotecaPanelComunicadosRoute: typeof BibliotecaPanelComunicadosRoute
  BibliotecaPanelConfiguracionRoute: typeof BibliotecaPanelConfiguracionRoute
  BibliotecaPanelNovedadesRoute: typeof BibliotecaPanelNovedadesRoute
  BibliotecaPanelRecursosRoute: typeof BibliotecaPanelRecursosRoute
  BibliotecaRecursoIdRoute: typeof BibliotecaRecursoIdRoute
  BibliotecaPanelIndexRoute: typeof BibliotecaPanelIndexRoute
}

const BibliotecaRouteRouteChildren: BibliotecaRouteRouteChildren = {
  BibliotecaAccesoRoute: BibliotecaAccesoRoute,
  BibliotecaAsistenteRoute: BibliotecaAsistenteRoute,
  BibliotecaCalendarioRoute: BibliotecaCalendarioRoute,
  BibliotecaEstudianteRoute: BibliotecaEstudianteRoute,
  BibliotecaFavoritosRoute: BibliotecaFavoritosRoute,
  BibliotecaInicioRoute: BibliotecaInicioRoute,
  BibliotecaNotificacionesRoute: BibliotecaNotificacionesRoute,
  BibliotecaNovedadesRoute: BibliotecaNovedadesRoute,
  BibliotecaPerfilRoute: BibliotecaPerfilRoute,
  BibliotecaIndexRoute: BibliotecaIndexRoute,
  BibliotecaIngresoRolRoute: BibliotecaIngresoRolRoute,
  BibliotecaMateriaCodeRoute: BibliotecaMateriaCodeRoute,
  BibliotecaPanelAdministracionRoute: BibliotecaPanelAdministracionRoute,
  BibliotecaPanelCalendarioRoute: BibliotecaPanelCalendarioRoute,
  BibliotecaPanelComunicadosRoute: BibliotecaPanelComunicadosRoute,
  BibliotecaPanelConfiguracionRoute: BibliotecaPanelConfiguracionRoute,
  BibliotecaPanelNovedadesRoute: BibliotecaPanelNovedadesRoute,
  BibliotecaPanelRecursosRoute: BibliotecaPanelRecursosRoute,
  BibliotecaRecursoIdRoute: BibliotecaRecursoIdRoute,
  BibliotecaPanelIndexRoute: BibliotecaPanelIndexRoute,
}

const BibliotecaRouteRouteWithChildren = BibliotecaRouteRoute._addFileChildren(
  BibliotecaRouteRouteChildren,
)

interface TuFuturoRouteRouteChildren {
  TuFuturoAdminRoute: typeof TuFuturoAdminRoute
  TuFuturoAuthRoute: typeof TuFuturoAuthRoute
  TuFuturoBecasRoute: typeof TuFuturoBecasRoute
  TuFuturoCalendarioRoute: typeof TuFuturoCalendarioRoute
  TuFuturoCaminosRoute: typeof TuFuturoCaminosRoute
  TuFuturoCarrerasRoute: typeof TuFuturoCarrerasRoute
  TuFuturoCompartirRoute: typeof TuFuturoCompartirRoute
  TuFuturoMapaRoute: typeof TuFuturoMapaRoute
  TuFuturoNoticiasRoute: typeof TuFuturoNoticiasRoute
  TuFuturoRecursosRoute: typeof TuFuturoRecursosRoute
  TuFuturoTestRoute: typeof TuFuturoTestRoute
  TuFuturoIndexRoute: typeof TuFuturoIndexRoute
  TuFuturoInstitucionesIdRoute: typeof TuFuturoInstitucionesIdRoute
  TuFuturoInstitucionesIndexRoute: typeof TuFuturoInstitucionesIndexRoute
}

const TuFuturoRouteRouteChildren: TuFuturoRouteRouteChildren = {
  TuFuturoAdminRoute: TuFuturoAdminRoute,
  TuFuturoAuthRoute: TuFuturoAuthRoute,
  TuFuturoBecasRoute: TuFuturoBecasRoute,
  TuFuturoCalendarioRoute: TuFuturoCalendarioRoute,
  TuFuturoCaminosRoute: TuFuturoCaminosRoute,
  TuFuturoCarrerasRoute: TuFuturoCarrerasRoute,
  TuFuturoCompartirRoute: TuFuturoCompartirRoute,
  TuFuturoMapaRoute: TuFuturoMapaRoute,
  TuFuturoNoticiasRoute: TuFuturoNoticiasRoute,
  TuFuturoRecursosRoute: TuFuturoRecursosRoute,
  TuFuturoTestRoute: TuFuturoTestRoute,
  TuFuturoIndexRoute: TuFuturoIndexRoute,
  TuFuturoInstitucionesIdRoute: TuFuturoInstitucionesIdRoute,
  TuFuturoInstitucionesIndexRoute: TuFuturoInstitucionesIndexRoute,
}

const TuFuturoRouteRouteWithChildren = TuFuturoRouteRoute._addFileChildren(
  TuFuturoRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BibliotecaRouteRoute: BibliotecaRouteRouteWithChildren,
  TuFuturoRouteRoute: TuFuturoRouteRouteWithChildren,
  AdminRoute: AdminRoute,
  HistoriaRoute: HistoriaRoute,
  InstitucionRoute: InstitucionRoute,
  MasRoute: MasRoute,
  ApiPublicBibliotecaSplatRoute: ApiPublicBibliotecaSplatRoute,
  ApiPublicMediaSplatRoute: ApiPublicMediaSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
