/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as TuFuturoRouteRouteImport } from './routes/tu-futuro/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TuFuturoCompartirRouteImport } from './routes/tu-futuro/compartir'
import { Route as TuFuturoBecasRouteImport } from './routes/tu-futuro/becas'
import { Route as ApiPublicMediaSplatRouteImport } from './routes/api/public/media/$'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const TuFuturoRouteRoute = TuFuturoRouteRouteImport.update({
  id: '/tu-futuro',
  path: '/tu-futuro',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TuFuturoCompartirRoute = TuFuturoCompartirRouteImport.update({
  id: '/compartir',
  path: '/compartir',
  getParentRoute: () => TuFuturoRouteRoute,
} as any)
const TuFuturoBecasRoute = TuFuturoBecasRouteImport.update({
  id: '/becas',
  path: '/becas',
  getParentRoute: () => TuFuturoRouteRoute,
} as any)
const ApiPublicMediaSplatRoute = ApiPublicMediaSplatRouteImport.update({
  id: '/api/public/media/$',
  path: '/api/public/media/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tu-futuro': typeof TuFuturoRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/tu-futuro/becas': typeof TuFuturoBecasRoute
  '/tu-futuro/compartir': typeof TuFuturoCompartirRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tu-futuro': typeof TuFuturoRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/tu-futuro/becas': typeof TuFuturoBecasRoute
  '/tu-futuro/compartir': typeof TuFuturoCompartirRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tu-futuro': typeof TuFuturoRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/tu-futuro/becas': typeof TuFuturoBecasRoute
  '/tu-futuro/compartir': typeof TuFuturoCompartirRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/tu-futuro'
    | '/admin'
    | '/tu-futuro/becas'
    | '/tu-futuro/compartir'
    | '/api/public/media/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/tu-futuro'
    | '/admin'
    | '/tu-futuro/becas'
    | '/tu-futuro/compartir'
    | '/api/public/media/$'
  id:
    | '__root__'
    | '/'
    | '/tu-futuro'
    | '/admin'
    | '/tu-futuro/becas'
    | '/tu-futuro/compartir'
    | '/api/public/media/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TuFuturoRouteRoute: typeof TuFuturoRouteRouteWithChildren
  AdminRoute: typeof AdminRoute
  ApiPublicMediaSplatRoute: typeof ApiPublicMediaSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tu-futuro': {
      id: '/tu-futuro'
      path: '/tu-futuro'
      fullPath: '/tu-futuro'
      preLoaderRoute: typeof TuFuturoRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tu-futuro/compartir': {
      id: '/tu-futuro/compartir'
      path: '/compartir'
      fullPath: '/tu-futuro/compartir'
      preLoaderRoute: typeof TuFuturoCompartirRouteImport
      parentRoute: typeof TuFuturoRouteRoute
    }
    '/tu-futuro/becas': {
      id: '/tu-futuro/becas'
      path: '/becas'
      fullPath: '/tu-futuro/becas'
      preLoaderRoute: typeof TuFuturoBecasRouteImport
      parentRoute: typeof TuFuturoRouteRoute
    }
    '/api/public/media/$': {
      id: '/api/public/media/$'
      path: '/api/public/media/$'
      fullPath: '/api/public/media/$'
      preLoaderRoute: typeof ApiPublicMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TuFuturoRouteRouteChildren {
  TuFuturoBecasRoute: typeof TuFuturoBecasRoute
  TuFuturoCompartirRoute: typeof TuFuturoCompartirRoute
}

const TuFuturoRouteRouteChildren: TuFuturoRouteRouteChildren = {
  TuFuturoBecasRoute: TuFuturoBecasRoute,
  TuFuturoCompartirRoute: TuFuturoCompartirRoute,
}

const TuFuturoRouteRouteWithChildren = TuFuturoRouteRoute._addFileChildren(
  TuFuturoRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TuFuturoRouteRoute: TuFuturoRouteRouteWithChildren,
  AdminRoute: AdminRoute,
  ApiPublicMediaSplatRoute: ApiPublicMediaSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
