// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { supabase } from "./client";

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
//
// Runs before EVERY server function call in the app (login de personal, asistente
// de IA, biblioteca, etc.), most of which don't need a Supabase user session at
// all. If building/using the Supabase browser client throws (e.g. missing
// VITE_SUPABASE_URL/VITE_SUPABASE_PUBLISHABLE_KEY at build time) this must not
// block those unrelated calls — degrade to "no auth header" instead of throwing.
export const attachSupabaseAuth = createMiddleware({ type: "function" }).client(
  async ({ next }) => {
    let token: string | undefined;
    try {
      const { data } = await supabase.auth.getSession();
      token = data.session?.access_token;
    } catch (error) {
      console.error("[Supabase] No se pudo obtener la sesión, se continúa sin token:", error);
    }
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    });
  },
);
